name: fuel_calculator_flutter
description: "Open source fuel calculator."

publish_to: "none"
version: 0.1.2+8

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.5
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  dynamic_color: ^1.7.0
  shared_preferences: ^2.3.5
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  objectbox_generator: any

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#423380"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_monochrome: "assets/icon/icon.png"

flutter:
  uses-material-design: true
